describe('FormProvider', () => {
  it('accepts the validateOnBlur setting via Formik', () => {})
  it('accepts the validateOnChange setting via Formik', () => {})
  it('renders a custom field validate icon', () => {})
  it('renders a custom placeholder input text color', () => {})
  it('formats the default grid columns', () => {})
  it('formats the default grid gap', () => {})
  it('renders the default labelStyle', () => {})
  it('renders the default errorStyle', () => {})
  it('configures field schema validation via validationSchema prop', () => {})
})
