export default {
  initialColorMode: "light",
  colors: {
    text: "#000",
    background: "#fff",
    primary: "#36313d",
    secondary: "#663399",
    accent: "#609",
    muted: "#f6f6f6f",
    bg_topbar: "#355cac",
    bg_header: "#fff",
    bg_mobilenav: "rgba(0, 0, 0, 0.9)",
    bg_sidenav: "#fdfdfd",
    bg_tabbar: "#fff",
    bg_footer: "#fff",
    modes: {
      dark: {
        text: "#fff",
        background: "#000",
        primary: "#0cf",
        secondary: "#09c",
        accent: "#609",
        muted: "#111",
        bg_topbar: "#609",
        bg_header: "#fff",
        bg_mobilenav: "#fff",
        bg_sidenav: "#fff",
        bg_tabbar: "#fff",
        bg_footer: "#fff",
      },
      purple: {
        text: "#fff",
        background: "#609",
        primary: "#0cf",
        secondary: "#09c",
        accent: "#609",
        muted: "#111",
        bg_topbar: "#609",
        bg_header: "#fff",
        bg_mobilenav: "#fff",
        bg_sidenav: "#fff",
        bg_tabbar: "#fff",
        bg_footer: "#fff",
      },
    },
  },
  fonts: {
    topbar: "system-ui, sans-serif",
    nav: "system-ui, sans-serif",
    body: "system-ui, sans-serif",
    heading: "system-ui, sans-serif",
    monospace: "Menlo, monospace",
  },
  shadows: {
    header: null,
    tabbar: null,
  },
  borders: {
    header: "1px solid #e6e6e6",
    footer: "1px solid #e6e6e6",
    tabbar: "1px solid gainsboro",
    sidenav: "1px solid #e6e6e6",
  },
}
