import { MakerMenu } from 'maker-ui'

export const menu: MakerMenu = [
  { divider: true, label: 'Overview', className: 'side-section-header' },
  { label: 'Getting Started', path: '/docs/getting-started' },
  { label: 'Maker UI Options', path: '/docs/maker-ui-options' },
  { label: 'Styling Components', path: '/docs/styling-components' },
  { divider: true, label: 'API Reference', className: 'side-section-header' },
  { label: 'Primitives', path: '/docs/primitives' },
  {
    label: 'Layout',
    path: '/docs/layout',
    className: 'api-btn',
    openNested: true,
    submenu: [
      { label: 'Layout', path: '/docs/layout/layout' },
      { label: 'Topbar', path: '/docs/layout/topbar' },
      { label: 'Header', path: '/docs/layout/header' },
      { label: 'Navbar', path: '/docs/layout/navbar' },
      { label: 'MobileMenu', path: '/docs/layout/mobile-menu' },
      { label: 'Content', path: '/docs/layout/content' },
      { label: 'Main', path: '/docs/layout/main' },
      { label: 'Section', path: '/docs/layout/section' },
      { label: 'SideNav', path: '/docs/layout/side-nav' },
      { label: 'Sidebar', path: '/docs/layout/sidebar' },
      { label: 'Footer', path: '/docs/layout/footer' },
      { label: 'ColorButton', path: '/docs/layout/color-button' },
      { label: 'Menus', path: '/docs/layout/menus' },
    ],
  },
  {
    label: 'Elements',
    path: '/docs/elements',
    className: 'api-btn',
    openNested: false,
    submenu: [
      { label: 'Accordion', path: '/docs/elements/accordion' },
      { label: 'Announcement', path: '/docs/elements/announcement' },
      { label: 'CookieNotice', path: '/docs/elements/cookie-notice' },
      { label: 'Modal', path: '/docs/elements/modal' },
      { label: 'Tabs', path: '/docs/elements/tabs' },
      { label: 'TableofContents', path: '/docs/elements/table-of-contents' },
      { label: 'PageTransition', path: '/docs/elements/page-transition' },
      { label: 'Generate', path: '/docs/elements/generate' },
      { label: 'Spinner', path: '/docs/elements/spinner' },
      { label: 'Popover', path: '/docs/elements/popover' },
      { label: 'Dropdown', path: '/docs/elements/dropdown' },
      { label: 'Tooltip', path: '/docs/elements/tooltip' },
    ],
  },
  {
    label: 'Forms',
    path: '/docs/elements',
    className: 'api-btn',
    openNested: false,
    submenu: [
      { label: 'Form', path: '/docs/forms/form' },
      { label: 'Fields', path: '/docs/forms/fields' },
      { label: 'Pagination', path: '/docs/forms/pagination' },
      { label: 'Validation', path: '/docs/forms/validation' },
      { label: 'Submission', path: '/docs/forms/submission' },
    ],
  },
  { label: 'Carousel', path: '/docs/carousel' },
  { label: 'Lightbox', path: '/docs/lightbox' },
  { label: 'Hooks', path: '/docs/hooks' },
  { label: 'Utilities', path: '/docs/utilities' },
  { divider: true, label: 'See Also', className: 'side-section-header' },
  { label: 'FAQs', path: '/docs/faqs' },
  { label: 'Contribute', path: '/docs/contribute' },
  { label: 'Credits', path: '/docs/credits' },
]
