name: Bug Report
description: File a bug report
title: 'Bug: '
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Report an issue with Maker UI within this repo.
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please provide a clear and concise description of what the bug is.
      placeholder: Something is broken!
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: I expected this to work.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual result
      description: What was the actual observed result?
      placeholder: This did not work.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Reproduction
      description: |
        Please provide a reproducible example. You can use the following template:

        - [Template for Layout (TypeScript + Next.js)](maker-ui-typescript-layout-next-bhon5d)
        - [Template for Components (TypeScript)](maker-ui-typescript-components-0bry2j)
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here (e.g. Maker UI version)
    validations:
      required: false
