export { default as FacebookIcon } from './Facebook'
export { default as InstagramIcon } from './Instagram'
export { default as LinkedinIcon } from './Linkedin'
export { default as TiktokIcon } from './Tiktok'
export { default as WebsiteIcon } from './Website'
export { default as XIcon } from './X'
export { default as YoutubeIcon } from './Youtube'
