export { default as DiscordIcon } from './Discord'
export { default as FacebookIcon } from './Facebook'
export { default as InstagramIcon } from './Instagram'
export { default as LinkedinIcon } from './Linkedin'
export { default as TiktokIcon } from './Tiktok'
export { default as TwitterIcon } from './Twitter'
export { default as WebsiteIcon } from './Website'
export { default as YoutubeIcon } from './Youtube'
