export default {
  initialColorMode: "light",
  colors: {
    text: "#000",
    background: "#fff",
    primary: "#36313d",
    secondary: "#355cac",
    accent: "#1858dc",
    muted: "#f6f6f6",
    border: "#e6e6e6",
    bg_topbar: "#355cac",
    bg_header: "#fff",
    bg_mobilenav: "rgba(0, 0, 0, 0.9)",
    bg_sidenav: "#f9f9f9",
    bg_tabbar: "#fff",
    bg_footer: "#fff",
    navlink: "#36313d",
    text_topbar: "#fff",
    modes: {
      dark: {
        text: "#fff",
        background: "#282c35",
        primary: "#0cf",
        secondary: "#fea7c4",
        accent: "#60d8d1",
        muted: "#111",
        border: "#404040",
        bg_topbar: "#fea6c8",
        bg_header: "#20232d",
        bg_mobilenav: "#1c1e27",
        bg_sidenav: "#1c1e27",
        bg_tabbar: "#1c1e27",
        bg_footer: "#1c1e27",
        navlink: "#fff",
        text_topbar: "#000",
      },
      silly: {
        text: "#fff",
        background: "#b562de",
        primary: "#0cf",
        secondary: "#09c",
        accent: "#67ca78",
        muted: "#111",
        border: "transparent",
        bg_topbar: "#32d69b",
        bg_header: "#fff",
        bg_mobilenav: "#fff",
        bg_sidenav: "#61b1f9",
        bg_tabbar: "#fff",
        bg_footer: "#ff6161",
        navlink: "#ff6161",
        text_topbar: "",
      },
    },
  },
  fonts: {
    body: "system-ui, sans-serif",
    heading: "system-ui, sans-serif",
    monospace: "Menlo, monospace",
  },
  shadows: {
    header: null,
    tabbar: null,
  },
}
