import { MenuProps } from 'maker-ui'

export const menu: MenuProps[] = [
  { label: 'Getting Started', path: '/' },
  { label: 'Maker UI Options', path: '/maker-ui-options' },
  { label: 'Primitives', path: '/primitives' },
  {
    label: 'Layout API',
    path: '/layout-api',
    openNested: true,
    submenu: [
      { label: 'Layout', path: '/layout' },
      { label: 'Topbar', path: '/topbar' },
      { label: 'Header', path: '/header' },
      { label: 'Navbar', path: '/navbar' },
      { label: 'MobileMenu', path: 'mobile-menu' },
      { label: 'Content', path: 'content' },
      { label: 'Main', path: 'main' },
      { label: 'Section', path: 'section' },
      { label: 'SideNav', path: 'side-nav' },
      { label: 'Sidebar', path: 'sidebar' },
      { label: 'Footer', path: 'footer' },
    ],
  },
  {
    label: 'Components API',
    path: '/components-api',
    openNested: true,
    submenu: [
      { label: 'ColorButton', path: '/color-button' },
      { label: 'CollapsibleMenu', path: '/collapsible-menu' },
      { label: 'Accordion', path: '/accordion' },
      { label: 'Announcement', path: '/announcement' },
      { label: 'CookieNotice', path: '/cookie-notice' },
      { label: 'Carousel', path: '/carousel' },
      { label: 'Lightbox', path: '/lightbox' },
      { label: 'Modal', path: '/modal' },
      { label: 'Tabs', path: '/tabs' },
      { label: 'TreeMenu', path: '/tree-menu' },
      { label: 'TableofContents', path: '/table-of-contents' },
      { label: 'PageTransition', path: '/page-transition' },
      { label: 'Generate', path: '/generate' },
      { label: 'Spinner', path: '/spinner' },
      { label: 'Popover', path: '/popover' },
      { label: 'Dropdown', path: '/dropdown' },
      { label: 'Tooltip', path: '/tooltip' },
    ],
  },
  { label: 'Hooks', path: '/hooks' },
  { label: 'Utilities', path: '/utilities' },
  { label: 'FAQs', path: '/hooks' },
  { label: 'Contribute', path: '/contribute' },
]
